ccflags-y += \
    -DCONFIG_PROVENCORE_NON_SECURE_IRQ=51 \
    -DCONFIG_PROVENCORE_IRQ_DOMAIN_NUMBER=0 \
    -DCONFIG_PROVENCORE_IRQ_TYPE_LEVEL_HIGH \
    -DCONFIG_PROVENCORE_SHARED_MMC \
    -DCONFIG_PROVENCORE_MMC_DEVICE="\"/dev/mmcblk1\"" \
    -DCONFIG_PROVENCORE_MMC_DEVID=0 \
    -DCONFIG_PROVENCORE_MMC_REMOTE_HOST
